apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-docker-app
  labels:
    app: python-docker-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-docker-app
  template:
    metadata:
      labels:
        app: python-docker-app
    spec:
      containers:
      - name: python-docker-app
        image: iambharathbs/python-docker-app:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: python-docker-app-service
spec:
  selector:
    app: python-docker-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
